/* File: _arrayderivedtypemodule.c
 * This file is auto-generated with f2py (version:1.22.2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Tue Mar 15 05:27:17 2022
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include <Python.h>
#include <stdarg.h>
#include "fortranobject.h"
/*need_includes0*/


/* custom abort handler - James Kermode <james.kermode@gmail.com> */
#include <setjmp.h>

#define ABORT_BUFFER_SIZE 1024
extern jmp_buf environment_buffer;
extern char abort_message[ABORT_BUFFER_SIZE];
void f90wrap_abort_(char *message, int len);
void f90wrap_abort_int_handler(int signum);

#include <stdlib.h>
#include <string.h>

jmp_buf environment_buffer;
char abort_message[ABORT_BUFFER_SIZE];

void f90wrap_abort_(char *message, int len_message)
{
  strncpy(abort_message, message, ABORT_BUFFER_SIZE);
  abort_message[ABORT_BUFFER_SIZE-1] = '\0';
  longjmp(environment_buffer, 0);
}

// copy of f90wrap_abort_ with a second underscore
// void (*f90wrap_abort__)(char *, int) = &f90wrap_abort_;
void f90wrap_abort__(char *message, int len_message)
{
  strncpy(abort_message, message, ABORT_BUFFER_SIZE);
  abort_message[ABORT_BUFFER_SIZE-1] = '\0';
  longjmp(environment_buffer, 0);
}


void f90wrap_abort_int_handler(int signum)
{
  char message[] = "Interrupt occured";
  f90wrap_abort_(message, strlen(message));
}

/* end of custom abort handler  */

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_arrayderivedtype_error;
static PyObject *_arrayderivedtype_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = _arrayderivedtype_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(f90wrap_type_ptmes__get__y,F90WRAP_TYPE_PTMES__GET__Y)(int*,int*);
extern void F_FUNC_US(f90wrap_type_ptmes__set__y,F90WRAP_TYPE_PTMES__SET__Y)(int*,int*);
extern void F_FUNC_US(f90wrap_type_ptmes_initialise,F90WRAP_TYPE_PTMES_INITIALISE)(int*);
extern void F_FUNC_US(f90wrap_type_ptmes_finalise,F90WRAP_TYPE_PTMES_FINALISE)(int*);
extern void F_FUNC_US(f90wrap_array_type__array_getitem__x,F90WRAP_ARRAY_TYPE__ARRAY_GETITEM__X)(int*,int*,int*);
extern void F_FUNC_US(f90wrap_array_type__array_setitem__x,F90WRAP_ARRAY_TYPE__ARRAY_SETITEM__X)(int*,int*,int*);
extern void F_FUNC_US(f90wrap_array_type__array_len__x,F90WRAP_ARRAY_TYPE__ARRAY_LEN__X)(int*,int*);
extern void F_FUNC_US(f90wrap_array_type_initialise,F90WRAP_ARRAY_TYPE_INITIALISE)(int*);
extern void F_FUNC_US(f90wrap_array_type_finalise,F90WRAP_ARRAY_TYPE_FINALISE)(int*);
extern void F_FUNC_US(f90wrap_recup_point,F90WRAP_RECUP_POINT)(int*);
extern void F_FUNC_US(f90wrap_xytest,F90WRAP_XYTEST)(void);
extern void F_FUNC_US(f90wrap_module_calcul__array_getitem__xarr,F90WRAP_MODULE_CALCUL__ARRAY_GETITEM__XARR)(int*,int*,int*);
extern void F_FUNC_US(f90wrap_module_calcul__array_setitem__xarr,F90WRAP_MODULE_CALCUL__ARRAY_SETITEM__XARR)(int*,int*,int*);
extern void F_FUNC_US(f90wrap_module_calcul__array_len__xarr,F90WRAP_MODULE_CALCUL__ARRAY_LEN__XARR)(int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/************************* f90wrap_type_ptmes__get__y *************************/
static char doc_f2py_rout__arrayderivedtype_f90wrap_type_ptmes__get__y[] = "\
f90wrap_y = f90wrap_type_ptmes__get__y(this)\n\nWrapper for ``f90wrap_type_ptmes__get__y``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (2)\n"
"\nReturns\n-------\n"
"f90wrap_y : int";
/* extern void F_FUNC_US(f90wrap_type_ptmes__get__y,F90WRAP_TYPE_PTMES__GET__Y)(int*,int*); */
static PyObject *f2py_rout__arrayderivedtype_f90wrap_type_ptmes__get__y(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
    int setjmpvalue; /* James Kermode - for setjmp */
/*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_tmp = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    int f90wrap_y = 0;
    static char *capi_kwlist[] = {"this",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_arrayderivedtype.f90wrap_type_ptmes__get__y",\
        capi_kwlist,&this_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=2;
    capi_this_intent |= F2PY_INTENT_IN;
    capi_this_tmp = array_from_pyobj(NPY_INT,this_Dims,this_Rank,capi_this_intent,this_capi);
  if (capi_this_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_arrayderivedtype_error,"failed in converting 1st argument `this' of _arrayderivedtype.f90wrap_type_ptmes__get__y to C/Fortran array" );
  } else {
    this = (int *)(capi_this_tmp->data);

    /* Processing variable f90wrap_y */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
PyOS_sighandler_t _npy_sig_save;
_npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
setjmpvalue = setjmp(environment_buffer);
if (setjmpvalue != 0) {
  PyOS_setsig(SIGINT, _npy_sig_save);
  PyErr_SetString(PyExc_RuntimeError, abort_message);
} else {
 /*callfortranroutine*/
                (*f2py_func)(this,&f90wrap_y);
 PyOS_setsig(SIGINT, _npy_sig_save);
}
/* End addition */
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",f90wrap_y);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f90wrap_y */
    if((PyObject *)capi_this_tmp!=this_capi) {
        Py_XDECREF(capi_this_tmp); }
    }  /*if (capi_this_tmp == NULL) ... else of this*/
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/********************* end of f90wrap_type_ptmes__get__y *********************/

/************************* f90wrap_type_ptmes__set__y *************************/
static char doc_f2py_rout__arrayderivedtype_f90wrap_type_ptmes__set__y[] = "\
f90wrap_type_ptmes__set__y(this,f90wrap_y)\n\nWrapper for ``f90wrap_type_ptmes__set__y``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (2)\n"
"f90wrap_y : input int";
/* extern void F_FUNC_US(f90wrap_type_ptmes__set__y,F90WRAP_TYPE_PTMES__SET__Y)(int*,int*); */
static PyObject *f2py_rout__arrayderivedtype_f90wrap_type_ptmes__set__y(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
    int setjmpvalue; /* James Kermode - for setjmp */
/*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_tmp = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    int f90wrap_y = 0;
    PyObject *f90wrap_y_capi = Py_None;
    static char *capi_kwlist[] = {"this","f90wrap_y",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:_arrayderivedtype.f90wrap_type_ptmes__set__y",\
        capi_kwlist,&this_capi,&f90wrap_y_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=2;
    capi_this_intent |= F2PY_INTENT_IN;
    capi_this_tmp = array_from_pyobj(NPY_INT,this_Dims,this_Rank,capi_this_intent,this_capi);
  if (capi_this_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_arrayderivedtype_error,"failed in converting 1st argument `this' of _arrayderivedtype.f90wrap_type_ptmes__set__y to C/Fortran array" );
  } else {
    this = (int *)(capi_this_tmp->data);

    /* Processing variable f90wrap_y */
        f2py_success = int_from_pyobj(&f90wrap_y,f90wrap_y_capi,"_arrayderivedtype.f90wrap_type_ptmes__set__y() 2nd argument (f90wrap_y) can't be converted to int");
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
PyOS_sighandler_t _npy_sig_save;
_npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
setjmpvalue = setjmp(environment_buffer);
if (setjmpvalue != 0) {
  PyOS_setsig(SIGINT, _npy_sig_save);
  PyErr_SetString(PyExc_RuntimeError, abort_message);
} else {
 /*callfortranroutine*/
                (*f2py_func)(this,&f90wrap_y);
 PyOS_setsig(SIGINT, _npy_sig_save);
}
/* End addition */
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of f90wrap_y*/
    /* End of cleaning variable f90wrap_y */
    if((PyObject *)capi_this_tmp!=this_capi) {
        Py_XDECREF(capi_this_tmp); }
    }  /*if (capi_this_tmp == NULL) ... else of this*/
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/********************* end of f90wrap_type_ptmes__set__y *********************/

/*********************** f90wrap_type_ptmes_initialise ***********************/
static char doc_f2py_rout__arrayderivedtype_f90wrap_type_ptmes_initialise[] = "\
this = f90wrap_type_ptmes_initialise()\n\nWrapper for ``f90wrap_type_ptmes_initialise``.\
\n\nReturns\n-------\n"
"this : rank-1 array('i') with bounds (2)";
/* extern void F_FUNC_US(f90wrap_type_ptmes_initialise,F90WRAP_TYPE_PTMES_INITIALISE)(int*); */
static PyObject *f2py_rout__arrayderivedtype_f90wrap_type_ptmes_initialise(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
    int setjmpvalue; /* James Kermode - for setjmp */
/*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_tmp = NULL;
    int capi_this_intent = 0;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:_arrayderivedtype.f90wrap_type_ptmes_initialise",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=2;
    capi_this_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    capi_this_tmp = array_from_pyobj(NPY_INT,this_Dims,this_Rank,capi_this_intent,Py_None);
  if (capi_this_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_arrayderivedtype_error,"failed in converting hidden `this' of _arrayderivedtype.f90wrap_type_ptmes_initialise to C/Fortran array" );
  } else {
    this = (int *)(capi_this_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
PyOS_sighandler_t _npy_sig_save;
_npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
setjmpvalue = setjmp(environment_buffer);
if (setjmpvalue != 0) {
  PyOS_setsig(SIGINT, _npy_sig_save);
  PyErr_SetString(PyExc_RuntimeError, abort_message);
} else {
 /*callfortranroutine*/
                (*f2py_func)(this);
 PyOS_setsig(SIGINT, _npy_sig_save);
}
/* End addition */
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_this_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /*if (capi_this_tmp == NULL) ... else of this*/
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************** end of f90wrap_type_ptmes_initialise ********************/

/************************ f90wrap_type_ptmes_finalise ************************/
static char doc_f2py_rout__arrayderivedtype_f90wrap_type_ptmes_finalise[] = "\
f90wrap_type_ptmes_finalise(this)\n\nWrapper for ``f90wrap_type_ptmes_finalise``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (2)";
/* extern void F_FUNC_US(f90wrap_type_ptmes_finalise,F90WRAP_TYPE_PTMES_FINALISE)(int*); */
static PyObject *f2py_rout__arrayderivedtype_f90wrap_type_ptmes_finalise(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
    int setjmpvalue; /* James Kermode - for setjmp */
/*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_tmp = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    static char *capi_kwlist[] = {"this",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_arrayderivedtype.f90wrap_type_ptmes_finalise",\
        capi_kwlist,&this_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=2;
    capi_this_intent |= F2PY_INTENT_IN;
    capi_this_tmp = array_from_pyobj(NPY_INT,this_Dims,this_Rank,capi_this_intent,this_capi);
  if (capi_this_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_arrayderivedtype_error,"failed in converting 1st argument `this' of _arrayderivedtype.f90wrap_type_ptmes_finalise to C/Fortran array" );
  } else {
    this = (int *)(capi_this_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
PyOS_sighandler_t _npy_sig_save;
_npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
setjmpvalue = setjmp(environment_buffer);
if (setjmpvalue != 0) {
  PyOS_setsig(SIGINT, _npy_sig_save);
  PyErr_SetString(PyExc_RuntimeError, abort_message);
} else {
 /*callfortranroutine*/
                (*f2py_func)(this);
 PyOS_setsig(SIGINT, _npy_sig_save);
}
/* End addition */
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_this_tmp!=this_capi) {
        Py_XDECREF(capi_this_tmp); }
    }  /*if (capi_this_tmp == NULL) ... else of this*/
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/********************* end of f90wrap_type_ptmes_finalise *********************/

/******************** f90wrap_array_type__array_getitem__x ********************/
static char doc_f2py_rout__arrayderivedtype_f90wrap_array_type__array_getitem__x[] = "\
xitem = f90wrap_array_type__array_getitem__x(f90wrap_this,f90wrap_i)\n\nWrapper for ``f90wrap_array_type__array_getitem__x``.\
\n\nParameters\n----------\n"
"f90wrap_this : input rank-1 array('i') with bounds (2)\n"
"f90wrap_i : input int\n"
"\nReturns\n-------\n"
"xitem : rank-1 array('i') with bounds (2)";
/* extern void F_FUNC_US(f90wrap_array_type__array_getitem__x,F90WRAP_ARRAY_TYPE__ARRAY_GETITEM__X)(int*,int*,int*); */
static PyObject *f2py_rout__arrayderivedtype_f90wrap_array_type__array_getitem__x(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
    int setjmpvalue; /* James Kermode - for setjmp */
/*decl*/

    int *f90wrap_this = NULL;
    npy_intp f90wrap_this_Dims[1] = {-1};
    const int f90wrap_this_Rank = 1;
    PyArrayObject *capi_f90wrap_this_tmp = NULL;
    int capi_f90wrap_this_intent = 0;
    PyObject *f90wrap_this_capi = Py_None;
    int f90wrap_i = 0;
    PyObject *f90wrap_i_capi = Py_None;
    int *xitem = NULL;
    npy_intp xitem_Dims[1] = {-1};
    const int xitem_Rank = 1;
    PyArrayObject *capi_xitem_tmp = NULL;
    int capi_xitem_intent = 0;
    static char *capi_kwlist[] = {"f90wrap_this","f90wrap_i",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:_arrayderivedtype.f90wrap_array_type__array_getitem__x",\
        capi_kwlist,&f90wrap_this_capi,&f90wrap_i_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable f90wrap_this */
    f90wrap_this_Dims[0]=2;
    capi_f90wrap_this_intent |= F2PY_INTENT_IN;
    capi_f90wrap_this_tmp = array_from_pyobj(NPY_INT,f90wrap_this_Dims,f90wrap_this_Rank,capi_f90wrap_this_intent,f90wrap_this_capi);
  if (capi_f90wrap_this_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_arrayderivedtype_error,"failed in converting 1st argument `f90wrap_this' of _arrayderivedtype.f90wrap_array_type__array_getitem__x to C/Fortran array" );
  } else {
    f90wrap_this = (int *)(capi_f90wrap_this_tmp->data);

    /* Processing variable f90wrap_i */
        f2py_success = int_from_pyobj(&f90wrap_i,f90wrap_i_capi,"_arrayderivedtype.f90wrap_array_type__array_getitem__x() 2nd argument (f90wrap_i) can't be converted to int");
    if (f2py_success) {
    /* Processing variable xitem */
    xitem_Dims[0]=2;
    capi_xitem_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    capi_xitem_tmp = array_from_pyobj(NPY_INT,xitem_Dims,xitem_Rank,capi_xitem_intent,Py_None);
  if (capi_xitem_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_arrayderivedtype_error,"failed in converting hidden `xitem' of _arrayderivedtype.f90wrap_array_type__array_getitem__x to C/Fortran array" );
  } else {
    xitem = (int *)(capi_xitem_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
PyOS_sighandler_t _npy_sig_save;
_npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
setjmpvalue = setjmp(environment_buffer);
if (setjmpvalue != 0) {
  PyOS_setsig(SIGINT, _npy_sig_save);
  PyErr_SetString(PyExc_RuntimeError, abort_message);
} else {
 /*callfortranroutine*/
                (*f2py_func)(f90wrap_this,&f90wrap_i,xitem);
 PyOS_setsig(SIGINT, _npy_sig_save);
}
/* End addition */
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_xitem_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /*if (capi_xitem_tmp == NULL) ... else of xitem*/
    /* End of cleaning variable xitem */
    } /*if (f2py_success) of f90wrap_i*/
    /* End of cleaning variable f90wrap_i */
    if((PyObject *)capi_f90wrap_this_tmp!=f90wrap_this_capi) {
        Py_XDECREF(capi_f90wrap_this_tmp); }
    }  /*if (capi_f90wrap_this_tmp == NULL) ... else of f90wrap_this*/
    /* End of cleaning variable f90wrap_this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/**************** end of f90wrap_array_type__array_getitem__x ****************/

/******************** f90wrap_array_type__array_setitem__x ********************/
static char doc_f2py_rout__arrayderivedtype_f90wrap_array_type__array_setitem__x[] = "\
f90wrap_array_type__array_setitem__x(f90wrap_this,f90wrap_i,xitem)\n\nWrapper for ``f90wrap_array_type__array_setitem__x``.\
\n\nParameters\n----------\n"
"f90wrap_this : input rank-1 array('i') with bounds (2)\n"
"f90wrap_i : input int\n"
"xitem : input rank-1 array('i') with bounds (2)";
/* extern void F_FUNC_US(f90wrap_array_type__array_setitem__x,F90WRAP_ARRAY_TYPE__ARRAY_SETITEM__X)(int*,int*,int*); */
static PyObject *f2py_rout__arrayderivedtype_f90wrap_array_type__array_setitem__x(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
    int setjmpvalue; /* James Kermode - for setjmp */
/*decl*/

    int *f90wrap_this = NULL;
    npy_intp f90wrap_this_Dims[1] = {-1};
    const int f90wrap_this_Rank = 1;
    PyArrayObject *capi_f90wrap_this_tmp = NULL;
    int capi_f90wrap_this_intent = 0;
    PyObject *f90wrap_this_capi = Py_None;
    int f90wrap_i = 0;
    PyObject *f90wrap_i_capi = Py_None;
    int *xitem = NULL;
    npy_intp xitem_Dims[1] = {-1};
    const int xitem_Rank = 1;
    PyArrayObject *capi_xitem_tmp = NULL;
    int capi_xitem_intent = 0;
    PyObject *xitem_capi = Py_None;
    static char *capi_kwlist[] = {"f90wrap_this","f90wrap_i","xitem",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|:_arrayderivedtype.f90wrap_array_type__array_setitem__x",\
        capi_kwlist,&f90wrap_this_capi,&f90wrap_i_capi,&xitem_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable f90wrap_this */
    f90wrap_this_Dims[0]=2;
    capi_f90wrap_this_intent |= F2PY_INTENT_IN;
    capi_f90wrap_this_tmp = array_from_pyobj(NPY_INT,f90wrap_this_Dims,f90wrap_this_Rank,capi_f90wrap_this_intent,f90wrap_this_capi);
  if (capi_f90wrap_this_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_arrayderivedtype_error,"failed in converting 1st argument `f90wrap_this' of _arrayderivedtype.f90wrap_array_type__array_setitem__x to C/Fortran array" );
  } else {
    f90wrap_this = (int *)(capi_f90wrap_this_tmp->data);

    /* Processing variable f90wrap_i */
        f2py_success = int_from_pyobj(&f90wrap_i,f90wrap_i_capi,"_arrayderivedtype.f90wrap_array_type__array_setitem__x() 2nd argument (f90wrap_i) can't be converted to int");
    if (f2py_success) {
    /* Processing variable xitem */
    xitem_Dims[0]=2;
    capi_xitem_intent |= F2PY_INTENT_IN;
    capi_xitem_tmp = array_from_pyobj(NPY_INT,xitem_Dims,xitem_Rank,capi_xitem_intent,xitem_capi);
  if (capi_xitem_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_arrayderivedtype_error,"failed in converting 3rd argument `xitem' of _arrayderivedtype.f90wrap_array_type__array_setitem__x to C/Fortran array" );
  } else {
    xitem = (int *)(capi_xitem_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
PyOS_sighandler_t _npy_sig_save;
_npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
setjmpvalue = setjmp(environment_buffer);
if (setjmpvalue != 0) {
  PyOS_setsig(SIGINT, _npy_sig_save);
  PyErr_SetString(PyExc_RuntimeError, abort_message);
} else {
 /*callfortranroutine*/
                (*f2py_func)(f90wrap_this,&f90wrap_i,xitem);
 PyOS_setsig(SIGINT, _npy_sig_save);
}
/* End addition */
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_xitem_tmp!=xitem_capi) {
        Py_XDECREF(capi_xitem_tmp); }
    }  /*if (capi_xitem_tmp == NULL) ... else of xitem*/
    /* End of cleaning variable xitem */
    } /*if (f2py_success) of f90wrap_i*/
    /* End of cleaning variable f90wrap_i */
    if((PyObject *)capi_f90wrap_this_tmp!=f90wrap_this_capi) {
        Py_XDECREF(capi_f90wrap_this_tmp); }
    }  /*if (capi_f90wrap_this_tmp == NULL) ... else of f90wrap_this*/
    /* End of cleaning variable f90wrap_this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/**************** end of f90wrap_array_type__array_setitem__x ****************/

/********************** f90wrap_array_type__array_len__x **********************/
static char doc_f2py_rout__arrayderivedtype_f90wrap_array_type__array_len__x[] = "\
f90wrap_n = f90wrap_array_type__array_len__x(f90wrap_this)\n\nWrapper for ``f90wrap_array_type__array_len__x``.\
\n\nParameters\n----------\n"
"f90wrap_this : input rank-1 array('i') with bounds (2)\n"
"\nReturns\n-------\n"
"f90wrap_n : int";
/* extern void F_FUNC_US(f90wrap_array_type__array_len__x,F90WRAP_ARRAY_TYPE__ARRAY_LEN__X)(int*,int*); */
static PyObject *f2py_rout__arrayderivedtype_f90wrap_array_type__array_len__x(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
    int setjmpvalue; /* James Kermode - for setjmp */
/*decl*/

    int *f90wrap_this = NULL;
    npy_intp f90wrap_this_Dims[1] = {-1};
    const int f90wrap_this_Rank = 1;
    PyArrayObject *capi_f90wrap_this_tmp = NULL;
    int capi_f90wrap_this_intent = 0;
    PyObject *f90wrap_this_capi = Py_None;
    int f90wrap_n = 0;
    static char *capi_kwlist[] = {"f90wrap_this",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_arrayderivedtype.f90wrap_array_type__array_len__x",\
        capi_kwlist,&f90wrap_this_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable f90wrap_n */
    /* Processing variable f90wrap_this */
    f90wrap_this_Dims[0]=2;
    capi_f90wrap_this_intent |= F2PY_INTENT_IN;
    capi_f90wrap_this_tmp = array_from_pyobj(NPY_INT,f90wrap_this_Dims,f90wrap_this_Rank,capi_f90wrap_this_intent,f90wrap_this_capi);
  if (capi_f90wrap_this_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_arrayderivedtype_error,"failed in converting 1st argument `f90wrap_this' of _arrayderivedtype.f90wrap_array_type__array_len__x to C/Fortran array" );
  } else {
    f90wrap_this = (int *)(capi_f90wrap_this_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
PyOS_sighandler_t _npy_sig_save;
_npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
setjmpvalue = setjmp(environment_buffer);
if (setjmpvalue != 0) {
  PyOS_setsig(SIGINT, _npy_sig_save);
  PyErr_SetString(PyExc_RuntimeError, abort_message);
} else {
 /*callfortranroutine*/
                (*f2py_func)(f90wrap_this,&f90wrap_n);
 PyOS_setsig(SIGINT, _npy_sig_save);
}
/* End addition */
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",f90wrap_n);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_f90wrap_this_tmp!=f90wrap_this_capi) {
        Py_XDECREF(capi_f90wrap_this_tmp); }
    }  /*if (capi_f90wrap_this_tmp == NULL) ... else of f90wrap_this*/
    /* End of cleaning variable f90wrap_this */
    /* End of cleaning variable f90wrap_n */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************** end of f90wrap_array_type__array_len__x ******************/

/*********************** f90wrap_array_type_initialise ***********************/
static char doc_f2py_rout__arrayderivedtype_f90wrap_array_type_initialise[] = "\
this = f90wrap_array_type_initialise()\n\nWrapper for ``f90wrap_array_type_initialise``.\
\n\nReturns\n-------\n"
"this : rank-1 array('i') with bounds (2)";
/* extern void F_FUNC_US(f90wrap_array_type_initialise,F90WRAP_ARRAY_TYPE_INITIALISE)(int*); */
static PyObject *f2py_rout__arrayderivedtype_f90wrap_array_type_initialise(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
    int setjmpvalue; /* James Kermode - for setjmp */
/*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_tmp = NULL;
    int capi_this_intent = 0;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:_arrayderivedtype.f90wrap_array_type_initialise",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=2;
    capi_this_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    capi_this_tmp = array_from_pyobj(NPY_INT,this_Dims,this_Rank,capi_this_intent,Py_None);
  if (capi_this_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_arrayderivedtype_error,"failed in converting hidden `this' of _arrayderivedtype.f90wrap_array_type_initialise to C/Fortran array" );
  } else {
    this = (int *)(capi_this_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
PyOS_sighandler_t _npy_sig_save;
_npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
setjmpvalue = setjmp(environment_buffer);
if (setjmpvalue != 0) {
  PyOS_setsig(SIGINT, _npy_sig_save);
  PyErr_SetString(PyExc_RuntimeError, abort_message);
} else {
 /*callfortranroutine*/
                (*f2py_func)(this);
 PyOS_setsig(SIGINT, _npy_sig_save);
}
/* End addition */
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_this_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /*if (capi_this_tmp == NULL) ... else of this*/
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************** end of f90wrap_array_type_initialise ********************/

/************************ f90wrap_array_type_finalise ************************/
static char doc_f2py_rout__arrayderivedtype_f90wrap_array_type_finalise[] = "\
f90wrap_array_type_finalise(this)\n\nWrapper for ``f90wrap_array_type_finalise``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (2)";
/* extern void F_FUNC_US(f90wrap_array_type_finalise,F90WRAP_ARRAY_TYPE_FINALISE)(int*); */
static PyObject *f2py_rout__arrayderivedtype_f90wrap_array_type_finalise(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
    int setjmpvalue; /* James Kermode - for setjmp */
/*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_tmp = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    static char *capi_kwlist[] = {"this",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_arrayderivedtype.f90wrap_array_type_finalise",\
        capi_kwlist,&this_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=2;
    capi_this_intent |= F2PY_INTENT_IN;
    capi_this_tmp = array_from_pyobj(NPY_INT,this_Dims,this_Rank,capi_this_intent,this_capi);
  if (capi_this_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_arrayderivedtype_error,"failed in converting 1st argument `this' of _arrayderivedtype.f90wrap_array_type_finalise to C/Fortran array" );
  } else {
    this = (int *)(capi_this_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
PyOS_sighandler_t _npy_sig_save;
_npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
setjmpvalue = setjmp(environment_buffer);
if (setjmpvalue != 0) {
  PyOS_setsig(SIGINT, _npy_sig_save);
  PyErr_SetString(PyExc_RuntimeError, abort_message);
} else {
 /*callfortranroutine*/
                (*f2py_func)(this);
 PyOS_setsig(SIGINT, _npy_sig_save);
}
/* End addition */
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_this_tmp!=this_capi) {
        Py_XDECREF(capi_this_tmp); }
    }  /*if (capi_this_tmp == NULL) ... else of this*/
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/********************* end of f90wrap_array_type_finalise *********************/

/**************************** f90wrap_recup_point ****************************/
static char doc_f2py_rout__arrayderivedtype_f90wrap_recup_point[] = "\
f90wrap_recup_point(x)\n\nWrapper for ``f90wrap_recup_point``.\
\n\nParameters\n----------\n"
"x : input rank-1 array('i') with bounds (2)";
/* extern void F_FUNC_US(f90wrap_recup_point,F90WRAP_RECUP_POINT)(int*); */
static PyObject *f2py_rout__arrayderivedtype_f90wrap_recup_point(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
    int setjmpvalue; /* James Kermode - for setjmp */
/*decl*/

    int *x = NULL;
    npy_intp x_Dims[1] = {-1};
    const int x_Rank = 1;
    PyArrayObject *capi_x_tmp = NULL;
    int capi_x_intent = 0;
    PyObject *x_capi = Py_None;
    static char *capi_kwlist[] = {"x",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_arrayderivedtype.f90wrap_recup_point",\
        capi_kwlist,&x_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable x */
    x_Dims[0]=2;
    capi_x_intent |= F2PY_INTENT_IN;
    capi_x_tmp = array_from_pyobj(NPY_INT,x_Dims,x_Rank,capi_x_intent,x_capi);
  if (capi_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_arrayderivedtype_error,"failed in converting 1st argument `x' of _arrayderivedtype.f90wrap_recup_point to C/Fortran array" );
  } else {
    x = (int *)(capi_x_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
PyOS_sighandler_t _npy_sig_save;
_npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
setjmpvalue = setjmp(environment_buffer);
if (setjmpvalue != 0) {
  PyOS_setsig(SIGINT, _npy_sig_save);
  PyErr_SetString(PyExc_RuntimeError, abort_message);
} else {
 /*callfortranroutine*/
                (*f2py_func)(x);
 PyOS_setsig(SIGINT, _npy_sig_save);
}
/* End addition */
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_x_tmp!=x_capi) {
        Py_XDECREF(capi_x_tmp); }
    }  /*if (capi_x_tmp == NULL) ... else of x*/
    /* End of cleaning variable x */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************************* end of f90wrap_recup_point *************************/

/******************************* f90wrap_xytest *******************************/
static char doc_f2py_rout__arrayderivedtype_f90wrap_xytest[] = "\
f90wrap_xytest()\n\nWrapper for ``f90wrap_xytest``.\
\n";
/* extern void F_FUNC_US(f90wrap_xytest,F90WRAP_XYTEST)(void); */
static PyObject *f2py_rout__arrayderivedtype_f90wrap_xytest(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(void)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
    int setjmpvalue; /* James Kermode - for setjmp */
/*decl*/

    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:_arrayderivedtype.f90wrap_xytest",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
PyOS_sighandler_t _npy_sig_save;
_npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
setjmpvalue = setjmp(environment_buffer);
if (setjmpvalue != 0) {
  PyOS_setsig(SIGINT, _npy_sig_save);
  PyErr_SetString(PyExc_RuntimeError, abort_message);
} else {
 /*callfortranroutine*/
                (*f2py_func)();
 PyOS_setsig(SIGINT, _npy_sig_save);
}
/* End addition */
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*************************** end of f90wrap_xytest ***************************/

/***************** f90wrap_module_calcul__array_getitem__xarr *****************/
static char doc_f2py_rout__arrayderivedtype_f90wrap_module_calcul__array_getitem__xarr[] = "\
xarritem = f90wrap_module_calcul__array_getitem__xarr(dummy_this,f90wrap_i)\n\nWrapper for ``f90wrap_module_calcul__array_getitem__xarr``.\
\n\nParameters\n----------\n"
"dummy_this : input rank-1 array('i') with bounds (2)\n"
"f90wrap_i : input int\n"
"\nReturns\n-------\n"
"xarritem : rank-1 array('i') with bounds (2)";
/* extern void F_FUNC_US(f90wrap_module_calcul__array_getitem__xarr,F90WRAP_MODULE_CALCUL__ARRAY_GETITEM__XARR)(int*,int*,int*); */
static PyObject *f2py_rout__arrayderivedtype_f90wrap_module_calcul__array_getitem__xarr(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
    int setjmpvalue; /* James Kermode - for setjmp */
/*decl*/

    int *dummy_this = NULL;
    npy_intp dummy_this_Dims[1] = {-1};
    const int dummy_this_Rank = 1;
    PyArrayObject *capi_dummy_this_tmp = NULL;
    int capi_dummy_this_intent = 0;
    PyObject *dummy_this_capi = Py_None;
    int f90wrap_i = 0;
    PyObject *f90wrap_i_capi = Py_None;
    int *xarritem = NULL;
    npy_intp xarritem_Dims[1] = {-1};
    const int xarritem_Rank = 1;
    PyArrayObject *capi_xarritem_tmp = NULL;
    int capi_xarritem_intent = 0;
    static char *capi_kwlist[] = {"dummy_this","f90wrap_i",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:_arrayderivedtype.f90wrap_module_calcul__array_getitem__xarr",\
        capi_kwlist,&dummy_this_capi,&f90wrap_i_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable dummy_this */
    dummy_this_Dims[0]=2;
    capi_dummy_this_intent |= F2PY_INTENT_IN;
    capi_dummy_this_tmp = array_from_pyobj(NPY_INT,dummy_this_Dims,dummy_this_Rank,capi_dummy_this_intent,dummy_this_capi);
  if (capi_dummy_this_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_arrayderivedtype_error,"failed in converting 1st argument `dummy_this' of _arrayderivedtype.f90wrap_module_calcul__array_getitem__xarr to C/Fortran array" );
  } else {
    dummy_this = (int *)(capi_dummy_this_tmp->data);

    /* Processing variable f90wrap_i */
        f2py_success = int_from_pyobj(&f90wrap_i,f90wrap_i_capi,"_arrayderivedtype.f90wrap_module_calcul__array_getitem__xarr() 2nd argument (f90wrap_i) can't be converted to int");
    if (f2py_success) {
    /* Processing variable xarritem */
    xarritem_Dims[0]=2;
    capi_xarritem_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    capi_xarritem_tmp = array_from_pyobj(NPY_INT,xarritem_Dims,xarritem_Rank,capi_xarritem_intent,Py_None);
  if (capi_xarritem_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_arrayderivedtype_error,"failed in converting hidden `xarritem' of _arrayderivedtype.f90wrap_module_calcul__array_getitem__xarr to C/Fortran array" );
  } else {
    xarritem = (int *)(capi_xarritem_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
PyOS_sighandler_t _npy_sig_save;
_npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
setjmpvalue = setjmp(environment_buffer);
if (setjmpvalue != 0) {
  PyOS_setsig(SIGINT, _npy_sig_save);
  PyErr_SetString(PyExc_RuntimeError, abort_message);
} else {
 /*callfortranroutine*/
                (*f2py_func)(dummy_this,&f90wrap_i,xarritem);
 PyOS_setsig(SIGINT, _npy_sig_save);
}
/* End addition */
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_xarritem_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /*if (capi_xarritem_tmp == NULL) ... else of xarritem*/
    /* End of cleaning variable xarritem */
    } /*if (f2py_success) of f90wrap_i*/
    /* End of cleaning variable f90wrap_i */
    if((PyObject *)capi_dummy_this_tmp!=dummy_this_capi) {
        Py_XDECREF(capi_dummy_this_tmp); }
    }  /*if (capi_dummy_this_tmp == NULL) ... else of dummy_this*/
    /* End of cleaning variable dummy_this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************* end of f90wrap_module_calcul__array_getitem__xarr *************/

/***************** f90wrap_module_calcul__array_setitem__xarr *****************/
static char doc_f2py_rout__arrayderivedtype_f90wrap_module_calcul__array_setitem__xarr[] = "\
f90wrap_module_calcul__array_setitem__xarr(dummy_this,f90wrap_i,xarritem)\n\nWrapper for ``f90wrap_module_calcul__array_setitem__xarr``.\
\n\nParameters\n----------\n"
"dummy_this : input rank-1 array('i') with bounds (2)\n"
"f90wrap_i : input int\n"
"xarritem : input rank-1 array('i') with bounds (2)";
/* extern void F_FUNC_US(f90wrap_module_calcul__array_setitem__xarr,F90WRAP_MODULE_CALCUL__ARRAY_SETITEM__XARR)(int*,int*,int*); */
static PyObject *f2py_rout__arrayderivedtype_f90wrap_module_calcul__array_setitem__xarr(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
    int setjmpvalue; /* James Kermode - for setjmp */
/*decl*/

    int *dummy_this = NULL;
    npy_intp dummy_this_Dims[1] = {-1};
    const int dummy_this_Rank = 1;
    PyArrayObject *capi_dummy_this_tmp = NULL;
    int capi_dummy_this_intent = 0;
    PyObject *dummy_this_capi = Py_None;
    int f90wrap_i = 0;
    PyObject *f90wrap_i_capi = Py_None;
    int *xarritem = NULL;
    npy_intp xarritem_Dims[1] = {-1};
    const int xarritem_Rank = 1;
    PyArrayObject *capi_xarritem_tmp = NULL;
    int capi_xarritem_intent = 0;
    PyObject *xarritem_capi = Py_None;
    static char *capi_kwlist[] = {"dummy_this","f90wrap_i","xarritem",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|:_arrayderivedtype.f90wrap_module_calcul__array_setitem__xarr",\
        capi_kwlist,&dummy_this_capi,&f90wrap_i_capi,&xarritem_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable dummy_this */
    dummy_this_Dims[0]=2;
    capi_dummy_this_intent |= F2PY_INTENT_IN;
    capi_dummy_this_tmp = array_from_pyobj(NPY_INT,dummy_this_Dims,dummy_this_Rank,capi_dummy_this_intent,dummy_this_capi);
  if (capi_dummy_this_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_arrayderivedtype_error,"failed in converting 1st argument `dummy_this' of _arrayderivedtype.f90wrap_module_calcul__array_setitem__xarr to C/Fortran array" );
  } else {
    dummy_this = (int *)(capi_dummy_this_tmp->data);

    /* Processing variable f90wrap_i */
        f2py_success = int_from_pyobj(&f90wrap_i,f90wrap_i_capi,"_arrayderivedtype.f90wrap_module_calcul__array_setitem__xarr() 2nd argument (f90wrap_i) can't be converted to int");
    if (f2py_success) {
    /* Processing variable xarritem */
    xarritem_Dims[0]=2;
    capi_xarritem_intent |= F2PY_INTENT_IN;
    capi_xarritem_tmp = array_from_pyobj(NPY_INT,xarritem_Dims,xarritem_Rank,capi_xarritem_intent,xarritem_capi);
  if (capi_xarritem_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_arrayderivedtype_error,"failed in converting 3rd argument `xarritem' of _arrayderivedtype.f90wrap_module_calcul__array_setitem__xarr to C/Fortran array" );
  } else {
    xarritem = (int *)(capi_xarritem_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
PyOS_sighandler_t _npy_sig_save;
_npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
setjmpvalue = setjmp(environment_buffer);
if (setjmpvalue != 0) {
  PyOS_setsig(SIGINT, _npy_sig_save);
  PyErr_SetString(PyExc_RuntimeError, abort_message);
} else {
 /*callfortranroutine*/
                (*f2py_func)(dummy_this,&f90wrap_i,xarritem);
 PyOS_setsig(SIGINT, _npy_sig_save);
}
/* End addition */
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_xarritem_tmp!=xarritem_capi) {
        Py_XDECREF(capi_xarritem_tmp); }
    }  /*if (capi_xarritem_tmp == NULL) ... else of xarritem*/
    /* End of cleaning variable xarritem */
    } /*if (f2py_success) of f90wrap_i*/
    /* End of cleaning variable f90wrap_i */
    if((PyObject *)capi_dummy_this_tmp!=dummy_this_capi) {
        Py_XDECREF(capi_dummy_this_tmp); }
    }  /*if (capi_dummy_this_tmp == NULL) ... else of dummy_this*/
    /* End of cleaning variable dummy_this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************* end of f90wrap_module_calcul__array_setitem__xarr *************/

/******************* f90wrap_module_calcul__array_len__xarr *******************/
static char doc_f2py_rout__arrayderivedtype_f90wrap_module_calcul__array_len__xarr[] = "\
f90wrap_n = f90wrap_module_calcul__array_len__xarr(dummy_this)\n\nWrapper for ``f90wrap_module_calcul__array_len__xarr``.\
\n\nParameters\n----------\n"
"dummy_this : input rank-1 array('i') with bounds (2)\n"
"\nReturns\n-------\n"
"f90wrap_n : int";
/* extern void F_FUNC_US(f90wrap_module_calcul__array_len__xarr,F90WRAP_MODULE_CALCUL__ARRAY_LEN__XARR)(int*,int*); */
static PyObject *f2py_rout__arrayderivedtype_f90wrap_module_calcul__array_len__xarr(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
    int setjmpvalue; /* James Kermode - for setjmp */
/*decl*/

    int *dummy_this = NULL;
    npy_intp dummy_this_Dims[1] = {-1};
    const int dummy_this_Rank = 1;
    PyArrayObject *capi_dummy_this_tmp = NULL;
    int capi_dummy_this_intent = 0;
    PyObject *dummy_this_capi = Py_None;
    int f90wrap_n = 0;
    static char *capi_kwlist[] = {"dummy_this",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_arrayderivedtype.f90wrap_module_calcul__array_len__xarr",\
        capi_kwlist,&dummy_this_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable f90wrap_n */
    /* Processing variable dummy_this */
    dummy_this_Dims[0]=2;
    capi_dummy_this_intent |= F2PY_INTENT_IN;
    capi_dummy_this_tmp = array_from_pyobj(NPY_INT,dummy_this_Dims,dummy_this_Rank,capi_dummy_this_intent,dummy_this_capi);
  if (capi_dummy_this_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_arrayderivedtype_error,"failed in converting 1st argument `dummy_this' of _arrayderivedtype.f90wrap_module_calcul__array_len__xarr to C/Fortran array" );
  } else {
    dummy_this = (int *)(capi_dummy_this_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
PyOS_sighandler_t _npy_sig_save;
_npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
setjmpvalue = setjmp(environment_buffer);
if (setjmpvalue != 0) {
  PyOS_setsig(SIGINT, _npy_sig_save);
  PyErr_SetString(PyExc_RuntimeError, abort_message);
} else {
 /*callfortranroutine*/
                (*f2py_func)(dummy_this,&f90wrap_n);
 PyOS_setsig(SIGINT, _npy_sig_save);
}
/* End addition */
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",f90wrap_n);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_dummy_this_tmp!=dummy_this_capi) {
        Py_XDECREF(capi_dummy_this_tmp); }
    }  /*if (capi_dummy_this_tmp == NULL) ... else of dummy_this*/
    /* End of cleaning variable dummy_this */
    /* End of cleaning variable f90wrap_n */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*************** end of f90wrap_module_calcul__array_len__xarr ***************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"f90wrap_type_ptmes__get__y",-1,{{-1}},0,(char *)F_FUNC_US(f90wrap_type_ptmes__get__y,F90WRAP_TYPE_PTMES__GET__Y),(f2py_init_func)f2py_rout__arrayderivedtype_f90wrap_type_ptmes__get__y,doc_f2py_rout__arrayderivedtype_f90wrap_type_ptmes__get__y},
    {"f90wrap_type_ptmes__set__y",-1,{{-1}},0,(char *)F_FUNC_US(f90wrap_type_ptmes__set__y,F90WRAP_TYPE_PTMES__SET__Y),(f2py_init_func)f2py_rout__arrayderivedtype_f90wrap_type_ptmes__set__y,doc_f2py_rout__arrayderivedtype_f90wrap_type_ptmes__set__y},
    {"f90wrap_type_ptmes_initialise",-1,{{-1}},0,(char *)F_FUNC_US(f90wrap_type_ptmes_initialise,F90WRAP_TYPE_PTMES_INITIALISE),(f2py_init_func)f2py_rout__arrayderivedtype_f90wrap_type_ptmes_initialise,doc_f2py_rout__arrayderivedtype_f90wrap_type_ptmes_initialise},
    {"f90wrap_type_ptmes_finalise",-1,{{-1}},0,(char *)F_FUNC_US(f90wrap_type_ptmes_finalise,F90WRAP_TYPE_PTMES_FINALISE),(f2py_init_func)f2py_rout__arrayderivedtype_f90wrap_type_ptmes_finalise,doc_f2py_rout__arrayderivedtype_f90wrap_type_ptmes_finalise},
    {"f90wrap_array_type__array_getitem__x",-1,{{-1}},0,(char *)F_FUNC_US(f90wrap_array_type__array_getitem__x,F90WRAP_ARRAY_TYPE__ARRAY_GETITEM__X),(f2py_init_func)f2py_rout__arrayderivedtype_f90wrap_array_type__array_getitem__x,doc_f2py_rout__arrayderivedtype_f90wrap_array_type__array_getitem__x},
    {"f90wrap_array_type__array_setitem__x",-1,{{-1}},0,(char *)F_FUNC_US(f90wrap_array_type__array_setitem__x,F90WRAP_ARRAY_TYPE__ARRAY_SETITEM__X),(f2py_init_func)f2py_rout__arrayderivedtype_f90wrap_array_type__array_setitem__x,doc_f2py_rout__arrayderivedtype_f90wrap_array_type__array_setitem__x},
    {"f90wrap_array_type__array_len__x",-1,{{-1}},0,(char *)F_FUNC_US(f90wrap_array_type__array_len__x,F90WRAP_ARRAY_TYPE__ARRAY_LEN__X),(f2py_init_func)f2py_rout__arrayderivedtype_f90wrap_array_type__array_len__x,doc_f2py_rout__arrayderivedtype_f90wrap_array_type__array_len__x},
    {"f90wrap_array_type_initialise",-1,{{-1}},0,(char *)F_FUNC_US(f90wrap_array_type_initialise,F90WRAP_ARRAY_TYPE_INITIALISE),(f2py_init_func)f2py_rout__arrayderivedtype_f90wrap_array_type_initialise,doc_f2py_rout__arrayderivedtype_f90wrap_array_type_initialise},
    {"f90wrap_array_type_finalise",-1,{{-1}},0,(char *)F_FUNC_US(f90wrap_array_type_finalise,F90WRAP_ARRAY_TYPE_FINALISE),(f2py_init_func)f2py_rout__arrayderivedtype_f90wrap_array_type_finalise,doc_f2py_rout__arrayderivedtype_f90wrap_array_type_finalise},
    {"f90wrap_recup_point",-1,{{-1}},0,(char *)F_FUNC_US(f90wrap_recup_point,F90WRAP_RECUP_POINT),(f2py_init_func)f2py_rout__arrayderivedtype_f90wrap_recup_point,doc_f2py_rout__arrayderivedtype_f90wrap_recup_point},
    {"f90wrap_xytest",-1,{{-1}},0,(char *)F_FUNC_US(f90wrap_xytest,F90WRAP_XYTEST),(f2py_init_func)f2py_rout__arrayderivedtype_f90wrap_xytest,doc_f2py_rout__arrayderivedtype_f90wrap_xytest},
    {"f90wrap_module_calcul__array_getitem__xarr",-1,{{-1}},0,(char *)F_FUNC_US(f90wrap_module_calcul__array_getitem__xarr,F90WRAP_MODULE_CALCUL__ARRAY_GETITEM__XARR),(f2py_init_func)f2py_rout__arrayderivedtype_f90wrap_module_calcul__array_getitem__xarr,doc_f2py_rout__arrayderivedtype_f90wrap_module_calcul__array_getitem__xarr},
    {"f90wrap_module_calcul__array_setitem__xarr",-1,{{-1}},0,(char *)F_FUNC_US(f90wrap_module_calcul__array_setitem__xarr,F90WRAP_MODULE_CALCUL__ARRAY_SETITEM__XARR),(f2py_init_func)f2py_rout__arrayderivedtype_f90wrap_module_calcul__array_setitem__xarr,doc_f2py_rout__arrayderivedtype_f90wrap_module_calcul__array_setitem__xarr},
    {"f90wrap_module_calcul__array_len__xarr",-1,{{-1}},0,(char *)F_FUNC_US(f90wrap_module_calcul__array_len__xarr,F90WRAP_MODULE_CALCUL__ARRAY_LEN__XARR),(f2py_init_func)f2py_rout__arrayderivedtype_f90wrap_module_calcul__array_len__xarr,doc_f2py_rout__arrayderivedtype_f90wrap_module_calcul__array_len__xarr},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "_arrayderivedtype",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit__arrayderivedtype(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = _arrayderivedtype_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module _arrayderivedtype (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("1.22.2");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module '_arrayderivedtype' is auto-generated with f2py (version:1.22.2).\nFunctions:\n"
"    f90wrap_y = f90wrap_type_ptmes__get__y(this)\n"
"    f90wrap_type_ptmes__set__y(this,f90wrap_y)\n"
"    this = f90wrap_type_ptmes_initialise()\n"
"    f90wrap_type_ptmes_finalise(this)\n"
"    xitem = f90wrap_array_type__array_getitem__x(f90wrap_this,f90wrap_i)\n"
"    f90wrap_array_type__array_setitem__x(f90wrap_this,f90wrap_i,xitem)\n"
"    f90wrap_n = f90wrap_array_type__array_len__x(f90wrap_this)\n"
"    this = f90wrap_array_type_initialise()\n"
"    f90wrap_array_type_finalise(this)\n"
"    f90wrap_recup_point(x)\n"
"    f90wrap_xytest()\n"
"    xarritem = f90wrap_module_calcul__array_getitem__xarr(dummy_this,f90wrap_i)\n"
"    f90wrap_module_calcul__array_setitem__xarr(dummy_this,f90wrap_i,xarritem)\n"
"    f90wrap_n = f90wrap_module_calcul__array_len__xarr(dummy_this)\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("1.22.2");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    _arrayderivedtype_error = PyErr_NewException ("_arrayderivedtype.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "__arrayderivedtype_error", _arrayderivedtype_error);
    Py_DECREF(_arrayderivedtype_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }














/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"_arrayderivedtype");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
