/* confdefs.h */
#define PACKAGE_NAME "fftw"
#define PACKAGE_TARNAME "fftw"
#define PACKAGE_VERSION "3.3.9"
#define PACKAGE_STRING "fftw 3.3.9"
#define PACKAGE_BUGREPORT "fftw@fftw.org"
#define PACKAGE_URL ""
#define PACKAGE "fftw"
#define VERSION "3.3.9"
#define FFTW_ENABLE_ALLOCA 1
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define HAVE_MPI 1
#define SIZEOF_MPI_FINT 4
#define STDC_HEADERS 1
#define HAVE_FCNTL_H 1
#define HAVE_FENV_H 1
#define HAVE_LIMITS_H 1
#define HAVE_MALLOC_H 1
#define HAVE_STDDEF_H 1
#define HAVE_SYS_TIME_H 1
#define TIME_WITH_SYS_TIME 1
#define HAVE_LONG_DOUBLE 1
#define SIZEOF_INT 4
#define SIZEOF_UNSIGNED_INT 4
#define SIZEOF_LONG 8
#define SIZEOF_UNSIGNED_LONG 8
#define SIZEOF_LONG_LONG 8
#define SIZEOF_UNSIGNED_LONG_LONG 8
#define SIZEOF_SIZE_T 8
#define SIZEOF_PTRDIFF_T 8
#define HAVE_PTRDIFF_T 1
#define HAVE_UINTPTR_T 1
#define SIZEOF_FLOAT 4
#define SIZEOF_DOUBLE 8
#define SIZEOF_FFTW_R2R_KIND 4
#define HAVE_ALLOCA_H 1
#define HAVE_ALLOCA 1
#define HAVE_VPRINTF 1
#define HAVE_LIBM 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_DRAND48 1
#define HAVE_SQRT 1
#define HAVE_MEMSET 1
#define HAVE_POSIX_MEMALIGN 1
#define HAVE_MEMALIGN 1
#define HAVE__MM_MALLOC 1
#define HAVE__MM_FREE 1
#define HAVE_CLOCK_GETTIME 1
#define HAVE_SYSCTL 1
#define HAVE_ABORT 1
#define HAVE_SINL 1
#define HAVE_COSL 1
#define HAVE_SNPRINTF 1
#define HAVE_MEMMOVE 1
#define HAVE_STRCHR 1
#define HAVE_GETPAGESIZE 1
#define HAVE_DECL_SINL 1
#define HAVE_DECL_COSL 1
#define HAVE_DECL_SINQ 0
#define HAVE_DECL_COSQ 0
#define HAVE_DECL_MEMALIGN 1
#define HAVE_DECL_DRAND48 1
#define HAVE_DECL_SRAND48 1
#define HAVE_DECL_POSIX_MEMALIGN 1
#define HAVE_ISNAN 1
#define F77_FUNC(name,NAME) name ## _
#define F77_FUNC_(name,NAME) name ## _
#define F77_FUNC_EQUIV 1
#define WITH_G77_WRAPPERS 1
#define FFTW_CC "icc -std=gnu99 -O3 -ansi-alias -malign-double"
