BEGIN {
S["am__EXEEXT_FALSE"]=""
S["am__EXEEXT_TRUE"]="#"
S["LTLIBOBJS"]=""
S["COMBINED_THREADS_FALSE"]=""
S["COMBINED_THREADS_TRUE"]="#"
S["SMP_FALSE"]=""
S["SMP_TRUE"]="#"
S["OPENMP_FALSE"]=""
S["OPENMP_TRUE"]="#"
S["THREADS_FALSE"]=""
S["THREADS_TRUE"]="#"
S["THREADLIBS"]=""
S["PTHREAD_CFLAGS"]=""
S["PTHREAD_LIBS"]=""
S["PTHREAD_CC"]=""
S["acx_pthread_config"]=""
S["OPENMP_CFLAGS"]=""
S["FLIBS"]=" -L/work/software/intel2018/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64_lin -L/work/software/intel2018/compilers_and_libraries_201"\
"8.3.222/linux/mkl/lib/intel64_lin -L/work/software/intel2018/compilers_and_libraries_2018.3.222/linux/ipp/lib/intel64 -L/work/software/intel2018/com"\
"pilers_and_libraries_2018.3.222/linux/tbb/lib/intel64/gcc4.7 -L/work/software/intel2018/compilers_and_libraries_2018.3.222/linux/daal/lib/intel64_li"\
"n -L/work/software/intel2018/compilers_and_libraries_2018.3.222/linux/daal/../tbb/lib/intel64_lin/gcc4.4 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/ -"\
"L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/ -L/lib/../lib64 -L/lib/../lib6"\
"4/ -L/usr/lib/../lib64 -L/usr/lib/../lib64/ -L/work/software/intel2018/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64_lin/ -L/work/so"\
"ftware/intel2018/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64_lin/ -L/work/software/intel2018/compilers_and_libraries_2018.3.222/linux/i"\
"pp/lib/intel64/ -L/work/software/intel2018/compilers_and_libraries_2018.3.222/linux/tbb/lib/intel64/gcc4.7/ -L/work/software/intel2018/compilers_and"\
"_libraries_2018.3.222/linux/daal/lib/intel64_lin/ -L/work/software/intel2018/compilers_and_libraries_2018.3.222/linux/daal/../tbb/lib/intel64_lin/gc"\
"c4.4/ -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../ -L/lib64 -L/lib/ -L/usr/lib64 -L/usr/lib -limf -lm -lifport -lifcoremt -lsvml -lipgo -lirc "\
"-lpthread -lirc_s -ldl"
S["ac_ct_F77"]=""
S["FFLAGS"]="-g"
S["F77"]="ifort"
S["INDENT"]=""
S["LIBQUADMATH"]=""
S["LIBOBJS"]=""
S["POW_LIB"]=""
S["ALLOCA"]=""
S["C_FFTW_R2R_KIND"]="C_INT32_T"
S["STACK_ALIGN_CFLAGS"]=""
S["NEON_CFLAGS"]=""
S["VSX_CFLAGS"]=""
S["ALTIVEC_CFLAGS"]=""
S["KCVI_CFLAGS"]=""
S["AVX512_CFLAGS"]=""
S["AVX2_CFLAGS"]=""
S["AVX_CFLAGS"]=""
S["SSE2_CFLAGS"]=""
S["MPI_FALSE"]="#"
S["MPI_TRUE"]=""
S["C_MPI_FINT"]="C_INT32_T"
S["MPIRUN"]="mpirun"
S["MPILIBS"]=" "
S["MPICC"]="mpiicc"
S["OCAMLBUILD"]=""
S["CPP"]="icc -std=gnu99 -E"
S["LT_SYS_LIBRARY_PATH"]=""
S["OTOOL64"]=""
S["OTOOL"]=""
S["LIPO"]=""
S["NMEDIT"]=""
S["DSYMUTIL"]=""
S["MANIFEST_TOOL"]=":"
S["RANLIB"]="ranlib"
S["ac_ct_AR"]="ar"
S["AR"]="ar"
S["NM"]="/usr/bin/nm -B"
S["ac_ct_DUMPBIN"]=""
S["DUMPBIN"]=""
S["LD"]="/usr/bin/ld -m elf_x86_64"
S["FGREP"]="/usr/bin/grep -F"
S["EGREP"]="/usr/bin/grep -E"
S["GREP"]="/usr/bin/grep"
S["SED"]="/usr/bin/sed"
S["LIBTOOL"]="$(SHELL) $(top_builddir)/libtool"
S["OBJDUMP"]="objdump"
S["DLLTOOL"]="dlltool"
S["AS"]="as"
S["LN_S"]="ln -s"
S["am__fastdepCC_FALSE"]="#"
S["am__fastdepCC_TRUE"]=""
S["CCDEPMODE"]="depmode=gcc3"
S["am__nodep"]="_no"
S["AMDEPBACKSLASH"]="\\"
S["AMDEP_FALSE"]="#"
S["AMDEP_TRUE"]=""
S["am__include"]="include"
S["DEPDIR"]=".deps"
S["OBJEXT"]="o"
S["EXEEXT"]=""
S["ac_ct_CC"]="icc"
S["CPPFLAGS"]=""
S["LDFLAGS"]=""
S["CFLAGS"]="-O3 -ansi-alias -malign-double"
S["CC"]="icc -std=gnu99"
S["PREC_SUFFIX"]=""
S["HAVE_GENERIC_SIMD256_FALSE"]=""
S["HAVE_GENERIC_SIMD256_TRUE"]="#"
S["HAVE_GENERIC_SIMD128_FALSE"]=""
S["HAVE_GENERIC_SIMD128_TRUE"]="#"
S["HAVE_NEON_FALSE"]=""
S["HAVE_NEON_TRUE"]="#"
S["HAVE_VSX_FALSE"]=""
S["HAVE_VSX_TRUE"]="#"
S["HAVE_ALTIVEC_FALSE"]=""
S["HAVE_ALTIVEC_TRUE"]="#"
S["HAVE_KCVI_FALSE"]=""
S["HAVE_KCVI_TRUE"]="#"
S["HAVE_AVX_128_FMA_FALSE"]=""
S["HAVE_AVX_128_FMA_TRUE"]="#"
S["AVX_128_FMA_CFLAGS"]=""
S["HAVE_AVX512_FALSE"]=""
S["HAVE_AVX512_TRUE"]="#"
S["HAVE_AVX2_FALSE"]=""
S["HAVE_AVX2_TRUE"]="#"
S["HAVE_AVX_FALSE"]=""
S["HAVE_AVX_TRUE"]="#"
S["HAVE_SSE2_FALSE"]=""
S["HAVE_SSE2_TRUE"]="#"
S["CHECK_PL_OPTS"]=""
S["PRECISION"]="d"
S["QUAD_FALSE"]=""
S["QUAD_TRUE"]="#"
S["LDOUBLE_FALSE"]=""
S["LDOUBLE_TRUE"]="#"
S["SINGLE_FALSE"]=""
S["SINGLE_TRUE"]="#"
S["BUILD_DOC_FALSE"]="#"
S["BUILD_DOC_TRUE"]=""
S["host_os"]="linux-gnu"
S["host_vendor"]="pc"
S["host_cpu"]="x86_64"
S["host"]="x86_64-pc-linux-gnu"
S["build_os"]="linux-gnu"
S["build_vendor"]="pc"
S["build_cpu"]="x86_64"
S["build"]="x86_64-pc-linux-gnu"
S["SHARED_VERSION_INFO"]="9:9:6"
S["MAINT"]="#"
S["MAINTAINER_MODE_FALSE"]=""
S["MAINTAINER_MODE_TRUE"]="#"
S["AM_BACKSLASH"]="\\"
S["AM_DEFAULT_VERBOSITY"]="1"
S["AM_DEFAULT_V"]="$(AM_DEFAULT_VERBOSITY)"
S["AM_V"]="$(V)"
S["am__untar"]="$${TAR-tar} xf -"
S["am__tar"]="$${TAR-tar} chof - \"$$tardir\""
S["AMTAR"]="$${TAR-tar}"
S["am__leading_dot"]="."
S["SET_MAKE"]=""
S["AWK"]="gawk"
S["mkdir_p"]="$(MKDIR_P)"
S["MKDIR_P"]="/usr/bin/mkdir -p"
S["INSTALL_STRIP_PROGRAM"]="$(install_sh) -c -s"
S["STRIP"]="strip"
S["install_sh"]="${SHELL} /work/home/xinyu/workplace/PhdProgram/aresPy/ares_lib/FFTW/fftw-3.3.9/install-sh"
S["MAKEINFO"]="${SHELL} /work/home/xinyu/workplace/PhdProgram/aresPy/ares_lib/FFTW/fftw-3.3.9/missing makeinfo"
S["AUTOHEADER"]="${SHELL} /work/home/xinyu/workplace/PhdProgram/aresPy/ares_lib/FFTW/fftw-3.3.9/missing autoheader"
S["AUTOMAKE"]="${SHELL} /work/home/xinyu/workplace/PhdProgram/aresPy/ares_lib/FFTW/fftw-3.3.9/missing automake-1.16"
S["AUTOCONF"]="${SHELL} /work/home/xinyu/workplace/PhdProgram/aresPy/ares_lib/FFTW/fftw-3.3.9/missing autoconf"
S["ACLOCAL"]="${SHELL} /work/home/xinyu/workplace/PhdProgram/aresPy/ares_lib/FFTW/fftw-3.3.9/missing aclocal-1.16"
S["VERSION"]="3.3.9"
S["PACKAGE"]="fftw"
S["CYGPATH_W"]="echo"
S["am__isrc"]=""
S["INSTALL_DATA"]="${INSTALL} -m 644"
S["INSTALL_SCRIPT"]="${INSTALL}"
S["INSTALL_PROGRAM"]="${INSTALL}"
S["target_alias"]=""
S["host_alias"]=""
S["build_alias"]=""
S["LIBS"]="-lm "
S["ECHO_T"]=""
S["ECHO_N"]="-n"
S["ECHO_C"]=""
S["DEFS"]="-DHAVE_CONFIG_H"
S["mandir"]="${datarootdir}/man"
S["localedir"]="${datarootdir}/locale"
S["libdir"]="${exec_prefix}/lib"
S["psdir"]="${docdir}"
S["pdfdir"]="${docdir}"
S["dvidir"]="${docdir}"
S["htmldir"]="${docdir}"
S["infodir"]="${datarootdir}/info"
S["docdir"]="${datarootdir}/doc/${PACKAGE_TARNAME}"
S["oldincludedir"]="/usr/include"
S["includedir"]="${prefix}/include"
S["runstatedir"]="${localstatedir}/run"
S["localstatedir"]="${prefix}/var"
S["sharedstatedir"]="${prefix}/com"
S["sysconfdir"]="${prefix}/etc"
S["datadir"]="${datarootdir}"
S["datarootdir"]="${prefix}/share"
S["libexecdir"]="${exec_prefix}/libexec"
S["sbindir"]="${exec_prefix}/sbin"
S["bindir"]="${exec_prefix}/bin"
S["program_transform_name"]="s,x,x,"
S["prefix"]="/work/home/xinyu/workplace/PhdProgram/aresPy/ares_lib/FFTW/fftw-3.3.9"
S["exec_prefix"]="${prefix}"
S["PACKAGE_URL"]=""
S["PACKAGE_BUGREPORT"]="fftw@fftw.org"
S["PACKAGE_STRING"]="fftw 3.3.9"
S["PACKAGE_VERSION"]="3.3.9"
S["PACKAGE_TARNAME"]="fftw"
S["PACKAGE_NAME"]="fftw"
S["PATH_SEPARATOR"]=":"
S["SHELL"]="/bin/sh"
S["am__quote"]=""
  for (key in S) S_is_set[key] = 1
  FS = ""

}
{
  line = $ 0
  nfields = split(line, field, "@")
  substed = 0
  len = length(field[1])
  for (i = 2; i < nfields; i++) {
    key = field[i]
    keylen = length(key)
    if (S_is_set[key]) {
      value = S[key]
      line = substr(line, 1, len) "" value "" substr(line, len + keylen + 3)
      len += length(value) + length(field[++i])
      substed = 1
    } else
      len += 1 + keylen
  }

  print line
}

