#!/bin/bash 
# testing variables 
days=10 
guest="Katie"
echo "$guest checked in $days days ago" 
days=5 
guest="Jessica" 
echo "$guest checked in $days"

testing=$(date)
echo $testing
testing=$(who)
echo $testing

today=$(date +%m%d)
ls -al > log.$today 
