!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.21.2)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrapf90wrap_om1c (nam, nuh, sp, dfp, voma, f2py_dfp&
     &_d0, f2py_dfp_d1, f2py_voma_d0, f2py_voma_d1)
                use mixer_module, only: om1c
      integer nam
      integer nuh
      real(kind=8) sp
      integer f2py_dfp_d0
      integer f2py_dfp_d1
      integer f2py_voma_d0
      integer f2py_voma_d1
      real(kind=8) dfp(f2py_dfp_d0,f2py_dfp_d1)
      real(kind=8) voma(f2py_voma_d0,f2py_voma_d1)
      interface
      
            subroutine f90wrap_om1c(nam,nuh,sp,dfp,voma) 
                use mixer_module, only: om1c
                integer, intent(in) :: nam
                integer, intent(in) :: nuh
                real(kind=8) :: sp
                real(kind=8), dimension(:, :) :: dfp
                real(kind=8), dimension(:, :) :: voma
            end subroutine f90wrap_om1c
      end interface
      call f90wrap_om1c(nam, nuh, sp, dfp, voma)
      end


      subroutine f2pywrapf90wrap_amst (beta, w0, nam, nuh, dxp, dfp, sp,&
     & xl, fl, voma, xn, f2py_dxp_d0, f2py_dxp_d1, f2py_dfp_d0, f2py_dfp&
     &_d1, f2py_xl_d0, f2py_fl_d0, f2py_voma_d0, f2py_voma_d1, f2py_xn_d&
     &0)
                use mixer_module, only: amst
      real(kind=8) beta
      real(kind=8) w0
      integer nam
      integer nuh
      real(kind=8) sp
      integer f2py_dxp_d0
      integer f2py_dxp_d1
      integer f2py_dfp_d0
      integer f2py_dfp_d1
      integer f2py_xl_d0
      integer f2py_fl_d0
      integer f2py_voma_d0
      integer f2py_voma_d1
      integer f2py_xn_d0
      real(kind=8) dxp(f2py_dxp_d0,f2py_dxp_d1)
      real(kind=8) dfp(f2py_dfp_d0,f2py_dfp_d1)
      real(kind=8) xl(f2py_xl_d0)
      real(kind=8) fl(f2py_fl_d0)
      real(kind=8) voma(f2py_voma_d0,f2py_voma_d1)
      real(kind=8) xn(f2py_xn_d0)
      interface
      
            subroutine f90wrap_amst(beta,w0,nam,nuh,dxp,dfp,sp,xl,fl,vom&
     &a,xn) 
                use mixer_module, only: amst
                real(kind=8) :: beta
                real(kind=8) :: w0
                integer, intent(in) :: nam
                integer, intent(in) :: nuh
                real(kind=8), dimension(:, :) :: dxp
                real(kind=8), dimension(:, :) :: dfp
                real(kind=8) :: sp
                real(kind=8), dimension(:) :: xl
                real(kind=8), dimension(:) :: fl
                real(kind=8), dimension(:, :) :: voma
                real(kind=8), dimension(:) :: xn
            end subroutine f90wrap_amst
      end interface
      call f90wrap_amst(beta, w0, nam, nuh, dxp, dfp, sp, xl, fl, voma, &
     &xn)
      end

